site_name: COMP423 Course Notes
theme:
  name: material
markdown_extensions:
  - pymdownx.highlight: # For highlighting code blocks
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:                # Adds links to headers
      permalink: true